name: starter_app
description: 'A starter Flutter app with Firebase, login, notifications, reusable widgets.'
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.1.1

  # State Management
  flutter_riverpod: ^3.1.0

  # Authentication Package
  workern_auth:
    path: ../../packages/workern_auth

  # Cloud Services Package
  workern_services:
    path: ../../packages/workern_services

  # Shared Widgets Package
  workern_widgets:
    path: ../../packages/workern_widgets

  # Notifications Package
  workern_notifications:
    path: ../../packages/workern_notifications

  # Billing Package
  workern_billing:
    path: ../../packages/workern_billing

  # UI
  shadcn_ui: ^0.50.2

  # Routing
  go_router: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  image_path_android: 'assets/icons/icon_1024.png'
  image_path_ios: 'assets/icons/icon_1024.png'
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#ffffff'
  web:
    generate: true
    image_path: 'assets/icons/icon_1024.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/icons/icon_1024.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icons/icon_1024.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/icons/icon_1024.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: false
