import 'dart:typed_data';
import 'package:firebase_ai/firebase_ai.dart' as ai;
import '../models/ai_model.dart';

/// Unified image generation service supporting multiple AI models
class ImageGenerationService {
  /// Generate an image from a text prompt
  ///
  /// Supports both Gemini image models (nano banana) and Imagen models
  ///
  /// Example:
  /// ```dart
  /// final service = ImageGenerationService();
  /// final imageBytes = await service.generateImage(
  ///   prompt: 'Professional product photo of fresh tomatoes',
  ///   model: AiModel.gemini25FlashImage,
  /// );
  /// ```
  Future<Uint8List?> generateImage({
    required String prompt,
    AiModel model = AiModel.gemini25FlashImage,
    GenerationConfig? config,
  }) async {
    try {
      if (!model.supports(ModelCapability.imageGeneration)) {
        throw ArgumentError(
          'Model ${model.displayName} does not support image generation',
        );
      }

      // For Gemini image models (nano banana)
      if (!model.isImagenModel) {
        return await _generateWithGeminiImageModel(prompt, model, config);
      }
      // For Imagen models
      else {
        return await _generateWithImagenModel(prompt, model);
      }
    } catch (e) {
      print('Error generating image with ${model.displayName}: $e');
      rethrow;
    }
  }

  /// Generate image with Gemini image models (nano banana)
  Future<Uint8List?> _generateWithGeminiImageModel(
    String prompt,
    AiModel model,
    GenerationConfig? config,
  ) async {
    // Create model with responseModalities configuration
    final aiModel = ai.FirebaseAI.googleAI().generativeModel(
      model: model.modelId,
      generationConfig: ai.GenerationConfig(
        temperature: config?.temperature,
        maxOutputTokens: config?.maxOutputTokens,
        topP: config?.topP,
        topK: config?.topK,
        stopSequences: config?.stopSequences,
        responseModalities: [
          ai.ResponseModalities.text,
          ai.ResponseModalities.image,
        ],
      ),
    );

    // Generate with image output
    final content = [ai.Content.text('Generate an image: $prompt')];
    final response = await aiModel.generateContent(content);

    // Extract image from response
    if (response.inlineDataParts.isNotEmpty) {
      return response.inlineDataParts.first.bytes;
    } else {
      print('No images were generated by the model.');
      return null;
    }
  }

  /// Generate image with Imagen models
  Future<Uint8List?> _generateWithImagenModel(
    String prompt,
    AiModel model,
  ) async {
    final aiModel = ai.FirebaseAI.googleAI().imagenModel(model: model.modelId);
    final response = await aiModel.generateImages(prompt);

    if (response.images.isNotEmpty) {
      // Note: Image extraction may vary by SDK version
      throw UnimplementedError(
        'Imagen model support coming soon. Use Gemini image models for now.',
      );
    }

    return null;
  }

  /// Generate an image with an input image (image-to-image)
  ///
  /// Takes an existing image and generates a new one based on the prompt
  /// Only works with Gemini image models
  ///
  /// Example:
  /// ```dart
  /// final newImage = await service.generateImageWithInput(
  ///   prompt: 'Make this photo look professional with studio lighting',
  ///   inputImage: existingImageBytes,
  ///   model: AiModel.gemini3ProImage,
  /// );
  /// ```
  Future<Uint8List?> generateImageWithInput({
    required String prompt,
    required Uint8List inputImage,
    String mimeType = 'image/jpeg',
    AiModel model = AiModel.gemini25FlashImage,
    GenerationConfig? config,
  }) async {
    try {
      if (model.isImagenModel) {
        throw ArgumentError(
          'Image-to-image generation only works with Gemini models',
        );
      }

      final aiModel = ai.FirebaseAI.googleAI().generativeModel(
        model: model.modelId,
        generationConfig: ai.GenerationConfig(
          temperature: config?.temperature,
          maxOutputTokens: config?.maxOutputTokens,
          topP: config?.topP,
          topK: config?.topK,
          stopSequences: config?.stopSequences,
          responseModalities: [
            ai.ResponseModalities.text,
            ai.ResponseModalities.image,
          ],
        ),
      );

      // Prepare content with both image and text
      final imagePart = ai.InlineDataPart(mimeType, inputImage);
      final promptPart = ai.TextPart('Generate an image: $prompt');

      final response = await aiModel.generateContent([
        ai.Content.multi([promptPart, imagePart]),
      ]);

      if (response.inlineDataParts.isNotEmpty) {
        return response.inlineDataParts.first.bytes;
      }

      return null;
    } catch (e) {
      print('Error generating image with input: $e');
      rethrow;
    }
  }

  /// Edit an existing image based on a text prompt
  ///
  /// Example:
  /// ```dart
  /// final editedImage = await service.editImage(
  ///   image: originalImageBytes,
  ///   prompt: 'Remove background and make it white',
  ///   model: AiModel.gemini3ProImage,
  /// );
  /// ```
  Future<Uint8List?> editImage({
    required Uint8List image,
    required String prompt,
    String mimeType = 'image/jpeg',
    AiModel model = AiModel.gemini25FlashImage,
    GenerationConfig? config,
  }) async {
    try {
      if (model.isImagenModel) {
        throw ArgumentError('Image editing only works with Gemini models');
      }

      final aiModel = ai.FirebaseAI.googleAI().generativeModel(
        model: model.modelId,
        generationConfig: ai.GenerationConfig(
          temperature: config?.temperature,
          maxOutputTokens: config?.maxOutputTokens,
          topP: config?.topP,
          topK: config?.topK,
          stopSequences: config?.stopSequences,
          responseModalities: [
            ai.ResponseModalities.text,
            ai.ResponseModalities.image,
          ],
        ),
      );

      final imagePart = ai.InlineDataPart(mimeType, image);
      final promptPart = ai.TextPart(prompt);

      final response = await aiModel.generateContent([
        ai.Content.multi([promptPart, imagePart]),
      ]);

      if (response.inlineDataParts.isNotEmpty) {
        return response.inlineDataParts.first.bytes;
      }

      return null;
    } catch (e) {
      print('Error editing image: $e');
      rethrow;
    }
  }

  /// Analyze an image and generate a description
  ///
  /// Example:
  /// ```dart
  /// final description = await service.analyzeImage(
  ///   image: productImageBytes,
  ///   prompt: 'Describe this product in detail for an e-commerce listing',
  /// );
  /// ```
  Future<String?> analyzeImage({
    required Uint8List image,
    required String prompt,
    String mimeType = 'image/jpeg',
    AiModel model = AiModel.gemini25ProVision,
  }) async {
    try {
      if (!model.supports(ModelCapability.imageUnderstanding) &&
          !model.supports(ModelCapability.multimodal)) {
        throw ArgumentError(
          'Model ${model.displayName} does not support image understanding',
        );
      }

      final aiModel = ai.FirebaseAI.googleAI().generativeModel(
        model: model.modelId,
      );

      final imagePart = ai.InlineDataPart(mimeType, image);
      final promptPart = ai.TextPart(prompt);

      final response = await aiModel.generateContent([
        ai.Content.multi([promptPart, imagePart]),
      ]);

      return response.text;
    } catch (e) {
      print('Error analyzing image: $e');
      rethrow;
    }
  }

  /// Generate variations of an existing image
  ///
  /// Creates multiple variations based on the original image and prompt
  Future<List<Uint8List>> generateVariations({
    required Uint8List originalImage,
    required String prompt,
    int count = 3,
    AiModel model = AiModel.gemini25FlashImage,
  }) async {
    final variations = <Uint8List>[];

    for (int i = 0; i < count; i++) {
      try {
        final variation = await generateImageWithInput(
          prompt: prompt,
          inputImage: originalImage,
          model: model,
        );

        if (variation != null) {
          variations.add(variation);
        }
      } catch (e) {
        print('Error generating variation $i: $e');
      }
    }

    return variations;
  }
}
