name: workern_utils
description: 'Utility functions and helpers for Workern Flutter applications.'
publish_to: 'none'
resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
