export const TASK_RESPONSE_STATE_APPROVED = 'APPROVED';
export const TASK_RESPONSE_STATE_REJECTED = 'REJECTED';
export const TASK_RESPONSE_STATE_PENDING = 'PENDING';
export const TASK_RESPONSE_STATE_PAID = 'PAID';

export const TASK_STATE_NOT_ACCEPTED = 'TASK_STATE_NOT_ACCEPTED';
export const TASK_STATE_ACCEPTED = 'TASK_STATE_ACCEPTED';
export const TASK_STATE_RETURNED = 'TASK_STATE_RETURNED';

export const TASK_ACCEPT_ERROR_MAX_DONE = 'TASK_ACCEPT_ERROR_MAX_DONE';
export const TASK_ACCEPT_ERROR_NOT_LEFT = 'TASK_ACCEPT_ERROR_NOT_LEFT';
export const TASK_ACCEPT_ERROR_HIGH_TRAFFIC = 'TASK_ACCEPT_ERROR_HIGH_TRAFFIC';

export const PROJECT_TYPE_CROWDSOURCING = 'crowdsourcing';

export const BASE_PROJECT_CROWDSOURCE = 'CROWDSOURCE';

export const TRANSACTION_STATE_SUCCESSFUL = 'SUCCESSFUL';
export const TRANSACTION_STATE_FAILED = 'FAILED';
export const TRANSACTION_STATE_PENDING = 'PENDING';
export const TRANSACTION_STATE_UNKNOWN = 'UNKOWN';

export const PROMISE_RESULT_DELETE_CRON = 111;

export const TRANSACTION_PROCESSOR_PAYTM = 'PAYTM';
export const TRANSACTION_PROCESSOR_PAYPAL = 'PAYPAL';
export const TRANSACTION_PROCESSOR_RAZORPAY = 'RAZORPAY';
export const TRANSACTION_PROCESSOR_RAZORPAY_X = 'RAZORPAYX';
//states for remove pending tasks
export const ACTION_TIME_LEFT = 'ACTION_TIME_LEFT';
export const ACTION_SUCCESSFUL = 'ACTION_SUCCESSFUL';
export const ACTION_DOC_DOESNT_EXIST = 'ACTION_DOC_DOESNT_EXIST';

export const WITHDRAWLMULTIPLIER = 0.965;
export const DEDUCTION_MULTIPLIER = 1.1;

export const FILE_TYPE_CSV = 'csv';
export const FILE_TYPE_JSON = 'json';

export const DAY_IN_MS = 86400000;

export const MIN_TASK_REWARD_IN_SUB_UNITS = 10; // Minimum task reward in cents
export const MIN_TASK_REWARD_USD = 0.1; // Minimum task reward in USD
