export const TRANSACTION_STATE_SUCCESSFUL = 'SUCCESSFUL';
export const TRANSACTION_STATE_FAILED = 'FAILED';
export const TRANSACTION_STATE_PENDING = 'PENDING';
export const TRANSACTION_STATE_UNKNOWN = 'UNKOWN';

export const PROMISE_RESULT_DELETE_CRON = 111;

export const TRANSACTION_PROCESSOR_PAYTM = 'PAYTM';
export const TRANSACTION_PROCESSOR_PAYPAL = 'PAYPAL';
export const TRANSACTION_PROCESSOR_RAZORPAY = 'RAZORPAY';
export const TRANSACTION_PROCESSOR_RAZORPAY_X = 'RAZORPAYX';
//states for remove pending tasks
export const ACTION_TIME_LEFT = 'ACTION_TIME_LEFT';
export const ACTION_SUCCESSFUL = 'ACTION_SUCCESSFUL';
export const ACTION_DOC_DOESNT_EXIST = 'ACTION_DOC_DOESNT_EXIST';

export const WITHDRAWLMULTIPLIER = 0.965;
export const DEDUCTION_MULTIPLIER = 1.1;

export const FILE_TYPE_CSV = 'csv';
export const FILE_TYPE_JSON = 'json';

export const DAY_IN_MS = 86400000;

