export enum TransactionProcessorID {
  RAZORPAY = 'RAZORPAY',
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
  PAYTM = 'PAYTM',
  RAZORPAYX = 'RAZORPAYX',
  LEMON_SQUEEZY = 'LEMON_SQUEEZY',
  DODO_PAYMENTS = 'DODO_PAYMENTS',
  PLAY_STORE = 'PLAY_STORE',
  APP_STORE = 'APP_STORE',
  REVENUE_CAT = 'REVENUE_CAT'
}
