name: workern_billing
description: A reusable billing package for in-app purchases on Play Store and App Store
version: 1.0.0
publish_to: none
resolution: workspace
environment:
  sdk: ^3.11.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  purchases_flutter: ^9.15.1
  flutter_riverpod: ^3.1.0
  workern_models:
    path: ../workern_models
  workern_services:
    path: ../workern_services
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  purchases_ui_flutter: ^9.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
