export enum TransactionReason {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWL = 'WITHDRAWL',
  BONUS_RECEIVED = 'BONUS_RECEIVED',
  OFFERING_REWARD = 'OFFERING_REWARD',
  APP_PRODUCT_PURCHASE = 'APP_PRODUCT_PURCHASE',
  SUBSCRIPTION_PAYMENT = 'SUBSCRIPTION_PAYMENT'
}
